name: Update docs-site submodule

on:
  push:
    branches:
      - main

jobs:
  update-docs-site:
    runs-on: ubuntu-latest

    steps:
      - name: Create temporary SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout node-sdk repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Clone docs-site repository with SSH
        run: |
          # Clone with SSH
          git clone git@github.com:Andamio-Platform/docs-site.git
          cd docs-site
          # Set local repository to use SSH
          git remote set-url origin git@github.com:Andamio-Platform/docs-site.git

      - name: Update submodule to latest main
        working-directory: docs-site
        run: |
          # Initialize and update submodules using SSH
          if [ -f .gitmodules ]; then
            # If using SSH URLs, keep them as is
            git submodule init
            git submodule update
          else
            echo "No .gitmodules file found"
          fi

          # Get the latest commit hash from node-sdk main
          cd ..
          LATEST_COMMIT=$(git rev-parse HEAD)
          cd docs-site

          # Update the node-sdk submodule to the latest commit
          cd node-sdk || (mkdir -p node-sdk && cd node-sdk && git init)
          git fetch git@github.com:Andamio-Platform/node-sdk.git main
          git checkout $LATEST_COMMIT
          cd ..

      - name: Commit and push changes
        working-directory: docs-site
        run: |
          git add node-sdk
          git commit -m "Update node-sdk submodule to latest main commit $LATEST_COMMIT" || echo "No changes to commit"
          git push origin main

      - name: Trigger docs-site workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: Andamio-Platform/docs-site
          event-type: update-node-sdk
